#!/bin/bash

send(){


set -e

if [ "a$NAUTILUS_SCRIPT_CURRENT_URI" = "a" ] ; then
## 供测试使用
	name="lianxi2.png"
	url="test"	
else

	url=`echo "$NAUTILUS_SCRIPT_CURRENT_URI" | awk -F '//' '{print $NF}'`
	#echo $url > /tmp/temp.txt
	name=`echo "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS"|awk -F '/' '{print $NF}' `
fi
	cd $url
#name=`echo "/home/yuanjia/Desktop/Screenshot_from_2013-05-07_16:04:43.png"|awk -F '/' '{print $NF}'`
#echo $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS

#name="/home/yuanjia/Desktop/Screenshot_from_2013-05-07_16:04:43.png"

swift -A https://auth.sinas3.com/v1.0  -U 23o43wyk0j -K mik202mk0l21xxy3zkiiw450l13yhwl523y22l2i  upload yuanjiapicture $name

baseUrl="http://laoyuanjia-yuanjiapicture.stor.sinaapp.com"

echo -n $baseUrl/$name | xclip -selection CLIPBOARD

#/home/yuanjia/Desktop/GetVdiskLink/GetLink.py  $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS

#echo ""$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS"" >> /tmp/temp.txt
}





send

if [ $? = 0 ] ; then
	notify-send ["Send_to_SaePic"] "上传成功!"
else
	notify-send ["Send_to_SaePic"] "上传错误!"
fi
